import type { Metadata } from "next";
import "./globals.css";
import {Merriweather, Merriweather_Sans } from 'next/font/google';
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const merriweather = Merriweather({
  weight: ["300", "400", "700"],
  subsets: ['latin']
});
export const merriweatherSans = Merriweather_Sans({
  subsets: ['latin']
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweatherSans.className} ${merriweather.className} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
